#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
# smart-context e2e smoke test
#
# smart-context 是 npm 包扩展（入口 src/index.ts，无顶层 index.ts），
# run_pi_and_check 的递归查找依赖顶层 index.ts，无法识别它。
# 因此采用手动沙箱模式（参考 pi-rate-limiter）：拷贝 src + 创建 bridge
# index.ts + 链接 @zenone/* 本地包 + mock-llm。
#
# 验证要点：
#   1. smart-context + pi-lab 共存加载无 ERROR
#   2. compression-aggression 实验注册成功（pi-lab 日志）
#   3. /smart-context 命令可用
#   4. 无 ERROR 日志
# ──────────────────────────────────────────────────────────────────────────────

set -euo pipefail
ROOT_DIR="${ROOT_DIR:?must be set by test runner}"

test_describe "smart-context"

# ====================================================================
# Helper: 搭建隔离测试沙箱
# ====================================================================
setup_sandbox() {
  local test_home="$1"
  shift

  local home_dir="$test_home/home"
  mkdir -p "$home_dir/.pi/agent/extensions" \
    "$test_home/.pi/extensions" \
    "$test_home/.pi/logs"

  # 基础设施扩展（pi-logger 是日志基础设施，始终拷贝）
  cp -r "$ROOT_DIR/extensions/meta/pi-logger" \
    "$test_home/.pi/extensions/pi-logger"

  for name in "$@"; do
    case "$name" in
    smart-context)
      # npm 包：拷贝源码 + 创建 bridge index.ts → src/index.ts
      cp -r "$ROOT_DIR/extensions/context/smart-context" \
        "$test_home/.pi/extensions/smart-context"
      cat >"$test_home/.pi/extensions/smart-context/index.ts" <<'BRIDGE'
// Auto-generated by e2e test - do not edit
export { default } from "./src/index.ts";
BRIDGE
      ;;
    pi-lab)
      cp -r "$ROOT_DIR/extensions/meta/pi-lab" \
        "$test_home/.pi/extensions/pi-lab"
      ;;
    pi-config)
      cp -r "$ROOT_DIR/extensions/meta/pi-config" \
        "$test_home/.pi/extensions/pi-config"
      ;;
    pi-session-tree)
      cp -r "$ROOT_DIR/extensions/meta/pi-session-tree" \
        "$test_home/.pi/extensions/pi-session-tree"
      ;;
    mock-llm)
      mkdir -p "$test_home/.pi/extensions/mock-llm"
      cp "$ROOT_DIR/test/e2e/helpers/mock-llm.ts" \
        "$test_home/.pi/extensions/mock-llm/index.ts"
      ;;
    esac
  done

  # 拷贝 pi-logger 配置
  if [[ -f "$ROOT_DIR/extensions/meta/pi-logger/pi-logger.json" ]]; then
    cp "$ROOT_DIR/extensions/meta/pi-logger/pi-logger.json" \
      "$test_home/.pi/pi-logger.json"
  fi

  # 建立 node_modules 本地包链接（使 import '@zenone/xxx' 可解析）
  mkdir -p "$test_home/node_modules/@zenone"
  for pkg in pi-logger pi-config pi-session-tree; do
    if [[ ! -e "$test_home/node_modules/@zenone/$pkg" ]]; then
      ln -sf "$ROOT_DIR/extensions/meta/$pkg" \
        "$test_home/node_modules/@zenone/$pkg"
    fi
  done

  # 拷贝共享 TUI 辅助模块（src/tui/）
  if [[ -d "$ROOT_DIR/src/tui" ]]; then
    mkdir -p "$test_home/src"
    cp -r "$ROOT_DIR/src/tui" "$test_home/src/tui"
  fi

  # 初始化 git（某些扩展需要 git 工作目录）
  if ! git -C "$test_home" rev-parse --git-dir &>/dev/null; then
    git -C "$test_home" init --initial-branch main &>/dev/null || true
  fi
}

# ====================================================================
# Helper: 在隔离沙箱中运行 pi（无会话模式）
# ====================================================================
run_pi() {
  local test_home="$1"
  local prompt="${2:-hi}"

  local stdout_file="$test_home/pi-stdout.log"

  cd "$test_home"
  set +e
  HOME="$test_home/home" pi -a --no-session -p "$prompt" \
    >"$stdout_file" 2>&1
  local ec=$?
  set -e
  cd "$ROOT_DIR"

  echo "=== pi exit code: $ec ==="
  return $ec
}

# ====================================================================
# 场景 1：smart-context + pi-lab 共存加载 + compression-aggression 注册
# ====================================================================
test_it "loads with pi-lab and registers compression-aggression experiment" <<'TEST'
  local slug="e2e-sc-s1-$$"
  local test_home="$ROOT_DIR/.pi/tmp/$slug"
  setup_sandbox "$test_home" mock-llm pi-lab smart-context

  run_pi "$test_home" "hi"
  local ec=$?

  # mock-llm 正常回复时 exit code 0；124 表示 LLM 未返回（打印模式下不阻塞）
  if [[ "$ec" -ne 0 && "$ec" -ne 124 ]]; then
    echo "FAIL: unexpected exit code $ec"
    cat "$test_home/pi-stdout.log"
    exit 1
  fi

  # 验证 stdout 无加载失败
  if grep -q "Failed to load extension" "$test_home/pi-stdout.log" 2>/dev/null; then
    echo "FAIL: extension load failure in stdout"
    grep "Failed to load extension" "$test_home/pi-stdout.log"
    exit 1
  fi

  # 验证 compression-aggression 实验注册成功（smart-context 的 lab 日志）
  # pi-logger 文件名格式：{source}_{YYYYMMDD}.log，source "smart-context:lab"
  # 经 sanitize（冒号→下划线）后为 smart-context_lab_YYYYMMDD.log
  local lab_logs="$test_home/.pi/logs/smart-context_lab_"*.log
  if grep -q "compression-aggression" $lab_logs 2>/dev/null; then
    echo "PASS: compression-aggression experiment registered"
  else
    echo "FAIL: compression-aggression not found in logs"
    ls -la "$test_home/.pi/logs/" 2>/dev/null || echo "(no logs dir)"
    exit 1
  fi

  rm -rf "$test_home" "$ROOT_DIR/.pi/tmp/${slug}"*
  exit 0
TEST

# ====================================================================
# 场景 2：/smart-context 命令可用
# ====================================================================
test_it "/smart-context command is callable" <<'TEST'
  local slug="e2e-sc-s2-$$"
  local test_home="$ROOT_DIR/.pi/tmp/$slug"
  setup_sandbox "$test_home" mock-llm smart-context

  run_pi "$test_home" "/smart-context"
  local ec=$?

  if [[ "$ec" -ne 0 && "$ec" -ne 124 ]]; then
    echo "FAIL: unexpected exit code $ec"
    cat "$test_home/pi-stdout.log"
    exit 1
  fi

  if grep -q "Failed to load extension" "$test_home/pi-stdout.log" 2>/dev/null; then
    echo "FAIL: extension load failure"
    grep "Failed to load extension" "$test_home/pi-stdout.log"
    exit 1
  fi

  echo "PASS: /smart-context executed without load error"
  rm -rf "$test_home" "$ROOT_DIR/.pi/tmp/${slug}"*
  exit 0
TEST

# ====================================================================
# 场景 3：无 ERROR 日志
# ====================================================================
test_it "no ERROR in logs" <<'TEST'
  local slug="e2e-sc-s3-$$"
  local test_home="$ROOT_DIR/.pi/tmp/$slug"
  setup_sandbox "$test_home" mock-llm pi-lab smart-context

  run_pi "$test_home" "hi"
  local ec=$?

  if [[ "$ec" -ne 0 && "$ec" -ne 124 ]]; then
    echo "FAIL: unexpected exit code $ec"
    exit 1
  fi

  local logs_dir="$test_home/.pi/logs"
  if [[ -d "$logs_dir" ]]; then
    if grep -rq "ERROR" "$logs_dir" 2>/dev/null; then
      echo "FAIL: Found ERROR in logs"
      grep -r "ERROR" "$logs_dir" 2>/dev/null | head -10
      exit 1
    fi
    echo "PASS: No ERROR in logs"
  else
    echo "WARN: No logs directory found"
  fi

  rm -rf "$test_home" "$ROOT_DIR/.pi/tmp/${slug}"*
  exit 0
TEST
