/**
 * scripts/lib/bridge-builder.ts — npm 风格扩展的桥接 index.ts 生成模块
 *
 * 为 npm 风格扩展（有 package.json + "pi" 字段的目录）
 * 创建 index.ts → src/index.ts 的桥接，使 Pi 自动发现机制可以加载。
 *
 * 不输出日志——所有结果通过返回值传递。
 */

import { existsSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { isNpmPackageDir } from './utils.js';

// ============================================================================
// Types
// ============================================================================

export interface BridgeResult {
	created: number;
	skipped: number;
	failed: number;
	details: Array<{
		name: string;
		status: 'created' | 'skipped' | 'failed';
		reason?: string;
	}>;
}

export interface BridgeBuilderOptions {
	/** 模拟模式 —— 不实际写入文件 */
	dryRun?: boolean;
}

const BRIDGE_CONTENT =
	'// Auto-generated by sync-to-local-pi - do not edit\nexport { default } from "./src/index.ts";\n';

// ============================================================================
// BridgeBuilder
// ============================================================================

export class BridgeBuilder {
	private readonly dryRun: boolean;

	constructor(opts: BridgeBuilderOptions = {}) {
		this.dryRun = opts.dryRun ?? false;
	}

	/**
	 * 为所有 npm 风格的扩展资源创建桥接 index.ts。
	 *
	 * 检测策略（按优先级）：
	 *   1. explicitNames：显式指定的扩展名（来自 ProfileConfig.npmBuild）
	 *   2. target 目录已同步且检测为 npm 包
	 *   3. target 不存在时回退到 sourcePath 检测（dry-run 场景）
	 *   4. 验证 src/index.ts 入口存在
	 *
	 * 跳过条件：
	 *   - 桥接文件已存在且内容一致
	 *   - src/index.ts 不存在
	 *   - 不属于 npm 风格扩展
	 *
	 * @param explicitNames 显式指定的扩展名列表（来自 profile.npmBuild 配置）
	 */
	ensureBridges(
		resources: Array<{
			type: string;
			name: string;
			sourcePath: string;
			targetPath: string;
			isDirectory: boolean;
		}>,
		explicitNames?: string[],
	): BridgeResult {
		const explicitSet = explicitNames ? new Set(explicitNames) : new Set<string>();
		const details: BridgeResult['details'] = [];
		let created = 0;
		let skipped = 0;
		let failed = 0;

		for (const resource of resources) {
			if (resource.type !== 'extensions') continue;
			if (!resource.isDirectory) continue;

			const npmDir = resource.targetPath;

			// 判断是否为 npm 风格扩展（优先级：显式配置 > target 检测 > source 回退）
			const isExplicit = explicitSet.has(resource.name);
			const checkPath = existsSync(npmDir) ? npmDir : resource.sourcePath;
			const isNpmStyle = isExplicit || isNpmPackageDir(checkPath);

			if (!isNpmStyle) {
				continue;
			}

			if (!existsSync(npmDir)) {
				if (this.dryRun) {
					details.push({
						name: resource.name,
						status: 'created',
						reason: 'bridge would be created (dry-run)',
					});
					created++;
				} else {
					details.push({
						name: resource.name,
						status: 'skipped',
						reason: 'target directory does not exist',
					});
					skipped++;
				}
				continue;
			}

			const bridgePath = join(npmDir, 'index.ts');
			const srcEntry = join(npmDir, 'src', 'index.ts');

			if (this.dryRun) {
				if (!existsSync(bridgePath)) {
					details.push({
						name: resource.name,
						status: 'created',
						reason: 'bridge would be created (dry-run)',
					});
					created++;
				} else {
					details.push({
						name: resource.name,
						status: 'skipped',
						reason: 'bridge already exists',
					});
					skipped++;
				}
				continue;
			}

			// src/index.ts 必须是入口文件（在检查/覆盖桥接文件前先验证）
			if (!existsSync(srcEntry)) {
				details.push({
					name: resource.name,
					status: 'failed',
					reason: `src/index.ts not found in ${npmDir}`,
				});
				failed++;
				continue;
			}

			// 桥接已存在 —— 跳过或覆盖
			if (existsSync(bridgePath)) {
				try {
					const existingContent = readFileSync(bridgePath, 'utf8');
					if (existingContent === BRIDGE_CONTENT) {
						details.push({
							name: resource.name,
							status: 'skipped',
							reason: 'bridge already exists and is up-to-date',
						});
						skipped++;
						continue;
					}
					// 内容不匹配，覆盖
					writeFileSync(bridgePath, BRIDGE_CONTENT, 'utf8');
					details.push({
						name: resource.name,
						status: 'created',
						reason: 'bridge updated (content mismatch)',
					});
					created++;
					continue;
				} catch {
					// 读取失败，覆盖写入
					writeFileSync(bridgePath, BRIDGE_CONTENT, 'utf8');
					details.push({
						name: resource.name,
						status: 'created',
						reason: 'bridge rewritten (read failed)',
					});
					created++;
					continue;
				}
			}

			// 创建桥接
			try {
				writeFileSync(bridgePath, BRIDGE_CONTENT, 'utf8');
				details.push({
					name: resource.name,
					status: 'created',
					reason: undefined,
				});
				created++;
			} catch (err) {
				details.push({
					name: resource.name,
					status: 'failed',
					reason: `write failed: ${String(err)}`,
				});
				failed++;
			}
		}

		return { created, skipped, failed, details };
	}
}
